name: Terraform CI/CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  terraform-ci-cd:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"  # Specify your desired version

      - name: Run Terraform Module Release Action
        uses: HappyPathway/terraform-module-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: '.'

